### ISSUE TITLE
Object Respawn appears to be Local

### ISSUE THREAD

**Issue by HATExRecon** [bdunderscore/attach-to-me#37]
While Utilizing the respawn timer function, the game object seems to only return to its original position for the person who dropped it, but remains in the spot it was dropped for all other players.

**Comment by HATExRecon** [comment]
Update on this, it appears that undoing the removal of the object sync script on the base object when it is made attachable seems to fix the issue, though I'm not sure what the impact on network load will be.

**Comment by bdunderscore** [comment]
Having object sync on the base object will add a bunch of extra network load, yeah. I didn't find time to investigate this last weekend, but I'll try to dig into it soon - it's probably just a missing `RequestSerialization()` somewhere.

**Comment by bdunderscore** [comment]
Should be fixed in v1.1.2, thanks for the report!
